### ISSUE TITLE
SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by bmitchinson** [ljharb/ls-engines#21]
![image](https://user-images.githubusercontent.com/33632286/86280082-c3a8c300-bba0-11ea-8bc6-537981ca748a.png)

Node 13.14.0, `npx ls-engines`

**Comment by ljharb** [comment]
Hmm - it seems like it's failing on one of your nested package.jsons. I think the error is coming from inside npm's arborist (the core of this package). Is there any more info you can provide?

What happens if you run `find . -name package.json -exec echo {} \; -exec python -mjson.tool "{}" \; 2>&1 | grep "No JSON" -B 1`?

**Comment by ljharb** [comment]
ping @bmitchinson

**Comment by isaacs** [comment]
Fix:

```patch
diff --git a/get-node-versions.js b/get-node-versions.js
index 600e6b1..c059fde 100644
--- a/get-node-versions.js
+++ b/get-node-versions.js
@@ -3,6 +3,6 @@
 const getJSON = require('get-json');
 
 module.exports = async function getNodeVersions() {
-	const index = await getJSON('http://nodejs.org/dist/index.json');
+	const index = await getJSON('https://nodejs.org/dist/index.json');
 	return index.map(({ version }) => version);
 };

```
